- name: Install DNS server
  hosts: server
  become: yes

  tasks:
    - name: Install bind9
      apt:
        name: bind9
        state: latest

    - name: Copy DNS database
      copy: src=db.local dest=/etc/bind/db.local

    - name: Copy DNS config
      copy: src=named.conf.master dest=/etc/bind/named.conf.local

    - name: Restart the bind9 service
      service:
        name: bind9
        state: restarted
